
home:
    path: /
    controller: App\Controller\homeController::home

contact:
    path: /contact
    controller: App\Controller\InfoController::contact

about:
    path: /about
    controller: App\Controller\InfoController::about

inscription:
    path: /inscription
    controller: App\Controller\SecurityController::inscription

connexion:
    path: /connexion
    controller: App\Controller\SecurityController::connexion

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

myprofil:
    path: /myprofil
    controller: App\Controller\CommandeController::myprofil
    
categorie:
    path: /categorie
    controller: App\Controller\ProductController::categorie

bag:
    path: /bag
    controller: App\Controller\PaiementController::bag

bag_add:
    path: /bag/{id}
    controller: App\Controller\PaiementController::add

bag_remove:
    path: /bag/remove/{id}
    controller: App\Controller\PaiementController::remove

lister:
    path: /lister/{id}
    controller: App\Controller\ProductController::liste_produit


paiement:
    path: /paiement
    controller: App\Controller\PaiementController::paiement
    
inscriptionPro:
    path: /inscriptionPro
    controller: App\Controller\ProfessionnalController::inscriptionPro

connexionPro:
    path: /connexionPro
    controller: App\Controller\ProfessionnalController::connexionPro

choixCompte:
    path: /choixCompte
    controller: App\Controller\SecurityController::choixCompte

choixLogin:
    path: /choixLogin
    controller: App\Controller\SecurityController::choixLogin

profilPro:
    path: /profilPro
    controller: App\Controller\ProfessionnalController::profilPro

stats:
    path: /stats
    controller: App\Controller\ProfessionnalController::stats

addProduct:
    path: /addProduct
    controller: App\Controller\ProfessionnalController::addProduct



