home:
    path: /
    controller: App\Controller\homeController::home

contact:
    path: /contact
    controller: App\Controller\ContactController::contact

about:
    path: /about
    controller: App\Controller\AboutController::about

inscription:
    path: /inscription
    controller: App\Controller\SecurityController::inscription

connexion:
    path: /connexion
    controller: App\Controller\SecurityController::connexion

logout :
    path: /logout
    controller: App\Controller\SecurityController::logout
