
home:
    path: /
    controller: App\Controller\homeController::home

contact:
    path: /contact
    controller: App\Controller\InfoController::contact

about:
    path: /about
    controller: App\Controller\InfoController::about

inscription:
    path: /inscription
    controller: App\Controller\SecurityController::inscription

connexion:
    path: /connexion
    controller: App\Controller\SecurityController::connexion

logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

myprofil:
    path: /myprofil
    controller: App\Controller\CommandeController::myprofil
    
categorie:
    path: /categorie
    controller: App\Controller\ProductController::categorie

bag:
    path: /bag
    controller: App\Controller\BagController::bag

bag_add:
    path: /bag/{id}
    controller: App\Controller\BagController::add

bag_remove:
    path: /bag/remove/{id}
    controller: App\Controller\BagController::remove

lister:
    path: /lister/{id}
    controller: App\Controller\ProductController::liste_produit

<<<<<<< HEAD
paiement:
    path: /paiement
    controller: App\Controller\PaiementController::paiement
=======
inscriptionPro:
    path: /inscriptionPro
    controller: App\Controller\ProfessionnalController::inscriptionPro

connexionPro:
    path: /connexionPro
    controller: App\Controller\ProfessionnalController::connexionPro

>>>>>>> c4d934c6fae2d6acc739db0fabfa9a13cd05f304



